In [1]:
import pandas as pd

In [34]:
import pandas as pd
df = pd.read_csv('share/heme/hem_1_1k/results.csv')
df.mean(numeric_only=True)

plddt_0             0.565633
ptm_0               0.495475
plddt_1             0.566220
ptm_1               0.535016
cross_rmsd_mean     6.096893
cross_rmsd_std      2.169935
intra_rmsd0_mean    5.877107
intra_rmsd0_std     2.112882
intra_rmsd1_mean    5.292274
intra_rmsd1_std     1.659841
dtype: float64

In [35]:
df[(df.cross_rmsd_mean > 2) & (df.intra_rmsd0_mean < 1) & (df.intra_rmsd1_mean < 1)]

,sample,plddt_0,ptm_0,plddt_1,ptm_1,cross_rmsd_mean,cross_rmsd_std,intra_rmsd0_mean,intra_rmsd0_std,intra_rmsd1_mean,intra_rmsd1_std
87,design206,0.742863,0.682268,0.772303,0.817953,9.630365,0.178731,0.846571,0.147036,0.834351,0.309587
95,design225,0.690789,0.728178,0.724720,0.752196,2.757778,0.168815,0.610825,0.138142,0.568225,0.117012
165,design326,0.894044,0.935481,0.908250,0.944766,2.282209,0.071020,0.325879,0.061719,0.325549,0.069303
266,design457,0.611791,0.557611,0.859934,0.923103,2.700668,0.146394,0.983659,0.172897,0.373595,0.090214
296,design494,0.592824,0.635964,0.648358,0.707616,3.282579,0.271735,0.593319,0.077841,0.577473,0.105774
301,design499,0.684289,0.638977,0.810136,0.821322,6.978830,0.182525,0.878218,0.337060,0.532132,0.161248
370,design6,0.683604,0.688328,0.823356,0.870561,3.738751,0.298553,0.526513,0.100621,0.958398,0.249630
379,design616,0.621872,0.586846,0.656136,0.625622,6.148844,0.187126,0.802051,0.088253,0.889201,0.316853
383,design620,0.812005,0.804804,0.907544,0.942391,3.755672,0.084049,0.828070,0.391875,0.260805,0.046720
557,design999,0.668677,0.590943,0.708585,0.702140,4.074073,0.197403,0.864113,0.190286,0.834276,0.245895

In [7]:
import pandas as pd
df = pd.read_csv('share/top7/results.csv')
df.mean(numeric_only=True)

plddt_0                      0.651261
ptm_0                        0.587050
plddt_1                      0.698034
ptm_1                        0.643901
state0_target_iptm_mean      0.386855
state1_target_iptm_mean      0.467205
state1_effector_iptm_mean    0.344210
state0_target_iptm_std       0.072493
state1_target_iptm_std       0.082786
state1_effector_iptm_std     0.092698
cross_rmsd_mean              3.257954
cross_rmsd_std               1.006462
intra_rmsd0_mean             2.467427
intra_rmsd0_std              0.927688
intra_rmsd1_mean             2.084546
intra_rmsd1_std              0.820950
dtype: float64

In [22]:
df[(df.state1_target_iptm_mean > 0.6) & (df.state0_target_iptm_mean < 0.6) & (df.state1_effector_iptm_mean > 0.5) & (df.cross_rmsd_mean > 3) & (df.intra_rmsd0_mean < 2) & (df.intra_rmsd1_mean < 2)]

,sample,plddt_0,ptm_0,plddt_1,ptm_1,state0_target_iptm_mean,state1_target_iptm_mean,state1_effector_iptm_mean,state0_target_iptm_std,state1_target_iptm_std,state1_effector_iptm_std,cross_rmsd_mean,cross_rmsd_std,intra_rmsd0_mean,intra_rmsd0_std,intra_rmsd1_mean,intra_rmsd1_std
796,design815,0.673664,0.568996,0.882165,0.867831,0.165659,0.891161,0.657088,0.062830,0.006692,0.154400,3.012727,0.263643,1.758516,0.865017,0.736395,0.246537
811,design829,0.745501,0.567700,0.851553,0.766014,0.538323,0.786387,0.511612,0.105801,0.046543,0.109713,3.599560,0.561568,1.685169,0.563019,1.059395,0.244656
869,design881,0.572935,0.485465,0.858417,0.798954,0.118510,0.878231,0.621545,0.036589,0.009695,0.043547,12.495152,0.173853,1.079434,0.221445,0.785701,0.139376
926,design94,0.705777,0.572336,0.824519,0.806770,0.337057,0.648536,0.926063,0.026644,0.078850,0.002815,7.365346,0.244366,0.877596,0.296191,0.567780,0.135332

In [1]:
import pandas as pd
df = pd.read_csv('out/oqo_ca/results.csv')
df.mean(numeric_only=True)

plddt_0               0.686698
ptm_0                 0.173746
plddt_1               0.562364
ptm_1                 0.416516
plddt_2               0.602501
ptm_2                 0.248318
cross_rmsd01_mean    11.226299
cross_rmsd01_std      4.581000
cross_rmsd02_mean     5.777081
cross_rmsd02_std      4.242920
cross_rmsd12_mean    13.785048
cross_rmsd12_std      2.142022
intra_rmsd0_mean      6.528994
intra_rmsd0_std       4.617717
intra_rmsd1_mean      4.157187
intra_rmsd1_std       2.636499
intra_rmsd2_mean      2.916880
intra_rmsd2_std       1.258379
dtype: float64

In [2]:
a = 0.75
b = 1.25
df[
    (df.intra_rmsd0_mean < a) & \
    (df.intra_rmsd1_mean < a) & \
    (df.intra_rmsd2_mean < a) & \
    (df.cross_rmsd01_mean > b) & \
    (df.cross_rmsd12_mean > b) & \
    (df.cross_rmsd02_mean > b)
]

,sample,plddt_0,ptm_0,plddt_1,ptm_1,plddt_2,ptm_2,cross_rmsd01_mean,cross_rmsd01_std,cross_rmsd02_mean,cross_rmsd02_std,cross_rmsd12_mean,cross_rmsd12_std,intra_rmsd0_mean,intra_rmsd0_std,intra_rmsd1_mean,intra_rmsd1_std,intra_rmsd2_mean,intra_rmsd2_std
170,design251,0.751861,0.578059,0.848641,0.904488,0.864272,0.889864,1.479989,0.138360,2.899621,0.093755,2.427514,0.087525,0.531523,0.126357,0.313978,0.041861,0.206948,0.030538
215,design292,0.827815,0.598281,0.728717,0.733707,0.878165,0.816023,1.512639,0.153827,1.386852,0.107941,2.087698,0.113515,0.378436,0.085687,0.696791,0.204948,0.453449,0.159561